# Generated by Django 4.0.1 on 2022-02-04 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_rename_name_customer_first_name_customer_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='privacy_policy',
            field=models.BooleanField(null=True),
        ),
    ]
